[workspace]
resolver = "3"

members = [
    "rimgen",
    "rimfs",
    "rimpart",
    "rimio",
]

default-members = ["rimgen", "rimfs"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Killian Massa (Mki) <contact@mki.dev>"]
