[package]
name = "rimgen-layout"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rimfs = { path = "../rimfs" }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
uuid = { version = "1.17.0", features = ["v4", "serde"] }