[[partitions]]
name = "RIM EFI"
mountpoint = "efi"
size = "100M"
fs = "fat32"
bootable = true

[[partitions]]
name = "RIM FAT32"
mountpoint = "data/*"
size = "auto"
fs = "fat32"

[[partitions]]
name = "RIM EXFAT"
mountpoint = "data/*"
size = "300M"
fs = "exfat"

# [[partitions]]
# name = "RIM EXT4"
# mountpoint = "data/*"
# size = "300M"
# fs = "ext4"

# [[partitions]]
# name = "NATIVE NTFS"
# mountpoint = "data/*"
# size = "300M"
# fs = "ntfs"

# [[partitions]]
# name = "RIM RAW"
# size = "300M"
# fs = "raw"
